In [1]:
import os
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import torch
from sklearn.model_selection import train_test_split

In [2]:
#create custom data class

class CustomDataset(Dataset):
    def __init__(self, path):
        self.data = pd.read_csv(path, sep=",", header=1)
        
    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        sepal_length = torch.tensor(self.data.iloc[idx, 0])
        sepal_width = self.data.iloc[idx, 1]
        petal_length = self.data.iloc[idx, 2]
        petal_width = self.data.iloc[idx, 3] 
        label = self.data.iloc[idx, 4]
        
        tensor_data = torch.tensor([sepal_length,sepal_width,sepal_width,sepal_width],dtype=torch.float32)
        
        return tensor_data , label

In [3]:
#just my afwull way to seperate training and testing dataset
# 80% training , 20% Test

dataset = CustomDataset("./dataset/IRIS.csv")
train_dataset, val_dataset = torch.utils.data.random_split(dataset, [0.8, 0.2])
len(train_dataset),len(val_dataset)

(120, 29)

In [43]:
#create train_dataloader and test_dataloader
# 80% for training, 20% of data for testing -> 149*0.8 = 119.2 -> 120 , 29
batch_size = 5

train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True) 
test_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

In [44]:
#4 inputs and 3  outputs 
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_stack =  nn.Sequential(
         nn.Linear(4,128),
         nn.ReLU(),
         nn.Linear(128,64),
         nn.ReLU(),
         nn.Linear(64,3),
         )
    def forward(self, x):
        logits = self.linear_stack(x)
        return logits

In [45]:
#map labels into tensor of shape [1, 0, 0]
def transform_label(label_data):
    data = []
    for i in label_data:
        if i == "Iris-setosa":
            #data.append(torch.tensor([1,0,0], dtype=torch.float32))
            data.append(torch.tensor(0))
        if i == "Iris-versicolor": 
            #data.append(torch.tensor([0,1,0], dtype=torch.float32))
            data.append(torch.tensor(1))
        if i == "Iris-virginica":
            #data.append(torch.tensor([0,0,1], dtype=torch.float32))
            data.append(torch.tensor(2))
    return torch.stack(data)

In [46]:
X_train, train_labels = next(iter(train_loader))
#train_labels before mapping tesnors 
train_labels

('Iris-versicolor',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-versicolor')

In [47]:
#train_labels, X_train = next(iter(train_loader))
train_labels = transform_label(train_labels)
X_train.shape, train_labels.shape, X_train.dtype, train_labels.dtype
train_labels

tensor([1, 2, 0, 0, 1])

In [48]:
X_train, train_labels

(tensor([[5.4000, 3.0000, 3.0000, 3.0000],
         [7.9000, 3.8000, 3.8000, 3.8000],
         [5.1000, 3.8000, 3.8000, 3.8000],
         [4.6000, 3.2000, 3.2000, 3.2000],
         [5.6000, 2.9000, 2.9000, 2.9000]]),
 tensor([1, 2, 0, 0, 1]))

In [49]:
#create model
lr = 0.01
model = NeuralNetwork()
optim = torch.optim.Adam(model.parameters(), lr=lr)
loss = torch.nn.CrossEntropyLoss()
#loss = torch.nn.MSELoss()
#Weights are by default torch.32 not 64 --> error message 

In [ ]:
n_iters = 10000
steps = n_iters/10
LOSS = []
for epochs in range(n_iters):  
    for i,(inputs, labels) in enumerate(train_loader):
        out = model(inputs)
        train_labels = transform_label(labels)
        l = loss(out, train_labels)
        l.backward()
        #update weights
        optim.step()
        optim.zero_grad()
    LOSS.append(l.item())
    if epochs%steps == 0:
        print(f"\n epoch: {epochs+steps}/{n_iters}, loss: {sum(LOSS)/len(LOSS)}")
        #if i % 1 == 0:
            #print(f" steps: {i+1}, loss : {l.item()}")


 epoch: 1000.0/10000, loss: 0.5142971277236938

 epoch: 2000.0/10000, loss: 0.3958474592191433

 epoch: 3000.0/10000, loss: 0.39709252067651335

 epoch: 4000.0/10000, loss: 0.39857379008032967

 epoch: 5000.0/10000, loss: 0.39702378895415597

 epoch: 6000.0/10000, loss: 0.3947690560339501


In [51]:
#X_test, test_labels = next(iter(test_loader))
#test_labels = transform_label(test_labels)
#x_label_predicted = model(X_test)
#x_label_predicted, test_labels

In [ ]:
#""""
#def final_x(x_hat):
#    list_tensors = []
#    for i in x_hat:
#        print(i)
#        final_tensor = torch.zeros(1,3)
#        final_tensor[0:,i] = 1
#        list_tensors.append(final_tensor)
#    return torch.cat(list_tensors)
#    
#    # tensor[0:,1] = 4 to accses specific value 
#_, x_label_predicted_hat = torch.max(x_label_predicted,1)
#x_label_predicted_hat

In [53]:
#final_x = final_x(x_label_predicted_hat)

In [54]:
def get_accuracy(model_prediction, test_labels):
    idx = 0
    number_pred = 0
    counter = 0
    while idx < 10:
        print(f" \n Tensor[{idx+1}]")
        for i in range(3):
            print(f"model: {model_prediction[idx][i].item()}, label: {test_labels[idx][i].item()}")
            if model_prediction[idx][i].item() == test_labels[idx][i].item():

                counter += 1
                if counter == 3:
                    number_pred += 1
        counter = 0
          
        idx +=1
    accuracy = number_pred/10 *100
    return print(f"\naccuracy of model {number_pred/10 *100}%")

In [55]:
#get_accuracy(final_x, test_labels)

In [56]:
#test_loader = DataLoader(test_dataset, batch_size=10, shuffle=True)
import accuracy_model as ac
test_model_acc = ac.data_loader
test_model_acc.accuracy(model, test_loader, batch_size=10)

accuracy batch 0:
40.0%
accuracy batch 1:
80.0%
accuracy batch 2:
80.0%
accuracy batch 3:
100.0%
accuracy batch 4:
100.0%
accuracy batch 5:
100.0%
accuracy batch 6:
80.0%
accuracy batch 7:
80.0%
accuracy batch 8:
80.0%
accuracy batch 9:
80.0%
accuracy batch 10:
80.0%
accuracy batch 11:
60.0%
accuracy batch 12:
80.0%
accuracy batch 13:
100.0%
accuracy batch 14:
80.0%
accuracy batch 15:
100.0%
accuracy batch 16:
80.0%
accuracy batch 17:
80.0%
accuracy batch 18:
100.0%
accuracy batch 19:
100.0%
accuracy batch 20:
40.0%
accuracy batch 21:
60.0%
accuracy batch 22:
100.0%
accuracy batch 23:
80.0%
accuracy batch 24:
60.0%
accuracy batch 25:
80.0%
accuracy batch 26:
40.0%
accuracy batch 27:
100.0%
accuracy batch 28:
80.0%
accuracy batch 29:
100.0%

total accuracy of model 80.67%


In [57]:
# save model 
#torch.save(model.state_dict(), "./model")